[project]
id = "gates-app"
name = "Gates Control Application"
version = "1.0.0"

[build]
# Build configuration for buildpacks
[[build.buildpacks]]
id = "gcr.io/buildpacks/nodejs"
version = "latest"

[run]
# Runtime configuration
env = [
  "NODE_ENV=production",
  "PORT=3001"
]
